name: Qodana Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  qodana-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          sudo apt install -y tree
          tree -a -L 5 -I '.git'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2.1
        timeout-minutes: 30
        with:
          upload-result: true
          args: "--linter,jetbrains/qodana-jvm-community,--fail-threshold,100"
          use-caches: false

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
